/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.login;

import java.awt.Color;
import javax.swing.*;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author Bryan Andagoya
 */
public final class SignIn extends javax.swing.JFrame {

    private String defaultName = "Nombre";
    private String defaultLastName = "Apellido";
    private String defaultDocument = "Cédula de identidad";
    private String defaultEmail = "Correo electrónico";
    private String defaultPassword = "Contraseña";
    private String defaultConfirmPassword = "Confirmar contraseña";

    /**
     * Creates new form SignIn
     */
    public SignIn() {
        initComponents();
        configureWindow();
        configureComponents();
    }

    public void configureWindow() {
        setLocationRelativeTo(null);
    }

    public void configureComponents() {
//        //City combo box
//        for (int i = 0; i < cbx_city.getComponentCount(); i++) {
//            if (cbx_city.getComponent(i) instanceof JComponent) {
//                ((JComponent) cbx_city.getComponent(i)).setBorder(new EmptyBorder(0, 0, 0, 0));
//            }
//
//            if (cbx_city.getComponent(i) instanceof AbstractButton) {
//                ((AbstractButton) cbx_city.getComponent(i)).setBorderPainted(false);
//            }
//        }

        lbl_fields.requestFocus();
        cbx_city.setUI(new CustomizedComboBox());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        txt_name = new javax.swing.JTextField();
        txt_lastName = new javax.swing.JTextField();
        txt_document = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        pwd_confirmPassword = new javax.swing.JPasswordField();
        pwd_password = new javax.swing.JPasswordField();
        cbx_city = new javax.swing.JComboBox<>();
        chx_wantInformation = new javax.swing.JCheckBox();
        chx_acceptConditions = new javax.swing.JCheckBox();
        btn_signIn = new javax.swing.JButton();
        lbl_viewPassword1 = new javax.swing.JLabel();
        lbl_viewPassword2 = new javax.swing.JLabel();
        lbl_image = new javax.swing.JLabel();
        lbl_fields = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(254, 249, 231));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_name.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_name.setForeground(new java.awt.Color(204, 209, 209));
        txt_name.setText("Nombre");
        txt_name.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        txt_name.setSelectedTextColor(new java.awt.Color(253, 254, 254));
        txt_name.setSelectionColor(new java.awt.Color(229, 152, 102));
        txt_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_nameFocusLost(evt);
            }
        });
        txt_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_nameMousePressed(evt);
            }
        });
        mainPanel.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 280, 30));

        txt_lastName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_lastName.setForeground(new java.awt.Color(204, 209, 209));
        txt_lastName.setText("Apellido");
        txt_lastName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        txt_lastName.setSelectedTextColor(new java.awt.Color(253, 254, 254));
        txt_lastName.setSelectionColor(new java.awt.Color(229, 152, 102));
        txt_lastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_lastNameFocusLost(evt);
            }
        });
        txt_lastName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_lastNameMousePressed(evt);
            }
        });
        mainPanel.add(txt_lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 280, 30));

        txt_document.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_document.setForeground(new java.awt.Color(204, 209, 209));
        txt_document.setText("Cédula de identidad");
        txt_document.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        txt_document.setSelectedTextColor(new java.awt.Color(253, 254, 254));
        txt_document.setSelectionColor(new java.awt.Color(229, 152, 102));
        txt_document.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_documentFocusLost(evt);
            }
        });
        txt_document.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_documentMousePressed(evt);
            }
        });
        mainPanel.add(txt_document, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 280, 30));

        txt_email.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_email.setForeground(new java.awt.Color(204, 209, 209));
        txt_email.setText("Correo electrónico");
        txt_email.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        txt_email.setSelectedTextColor(new java.awt.Color(253, 254, 254));
        txt_email.setSelectionColor(new java.awt.Color(229, 152, 102));
        txt_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_emailFocusLost(evt);
            }
        });
        txt_email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_emailMousePressed(evt);
            }
        });
        mainPanel.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 280, 30));

        pwd_confirmPassword.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        pwd_confirmPassword.setForeground(new java.awt.Color(204, 209, 209));
        pwd_confirmPassword.setText("Confirmar contraseña");
        pwd_confirmPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        pwd_confirmPassword.setEchoChar((char)0);
        pwd_confirmPassword.setSelectedTextColor(new java.awt.Color(253, 254, 254));
        pwd_confirmPassword.setSelectionColor(new java.awt.Color(229, 152, 102));
        pwd_confirmPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwd_confirmPasswordFocusLost(evt);
            }
        });
        pwd_confirmPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pwd_confirmPasswordMousePressed(evt);
            }
        });
        mainPanel.add(pwd_confirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 280, 30));

        pwd_password.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        pwd_password.setForeground(new java.awt.Color(204, 209, 209));
        pwd_password.setText("Contraseña");
        pwd_password.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        pwd_password.setEchoChar((char)0);
        pwd_password.setSelectedTextColor(new java.awt.Color(253, 254, 254));
        pwd_password.setSelectionColor(new java.awt.Color(229, 152, 102));
        pwd_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwd_passwordFocusLost(evt);
            }
        });
        pwd_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pwd_passwordMousePressed(evt);
            }
        });
        mainPanel.add(pwd_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 280, 30));

        cbx_city.setBackground(new java.awt.Color(253, 254, 254));
        cbx_city.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbx_city.setForeground(new java.awt.Color(204, 209, 209));
        cbx_city.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ciudad", "Quito ", "Guayaquil", "Cuenca", "Ambato" }));
        cbx_city.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        cbx_city.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbx_city.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_cityItemStateChanged(evt);
            }
        });
        mainPanel.add(cbx_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 280, 30));

        chx_wantInformation.setText("Deseo recibir información de productos y servicios.");
        chx_wantInformation.setContentAreaFilled(false);
        chx_wantInformation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chx_wantInformation.setFocusPainted(false);
        mainPanel.add(chx_wantInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, -1, -1));

        chx_acceptConditions.setText("Acepto los terminos y condiciones.");
        chx_acceptConditions.setContentAreaFilled(false);
        chx_acceptConditions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chx_acceptConditions.setFocusPainted(false);
        mainPanel.add(chx_acceptConditions, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        btn_signIn.setBackground(new java.awt.Color(231, 76, 60));
        btn_signIn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_signIn.setForeground(new java.awt.Color(255, 255, 255));
        btn_signIn.setText("REGISTRAR");
        btn_signIn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_signIn.setBorderPainted(false);
        btn_signIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_signIn.setFocusPainted(false);
        btn_signIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_signInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_signInMouseExited(evt);
            }
        });
        mainPanel.add(btn_signIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, -1, -1));

        lbl_viewPassword1.setIcon(new ImageIcon("src/main/java/com/desarrollo/images/view.png"));
        lbl_viewPassword1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainPanel.add(lbl_viewPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 235, 20, 20));

        lbl_viewPassword2.setIcon(new ImageIcon("src/main/java/com/desarrollo/images/view.png"));
        lbl_viewPassword2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainPanel.add(lbl_viewPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 195, 20, 20));

        lbl_image.setIcon(new ImageIcon("src/main/java/com/desarrollo/images/signIn.jpg"));
        mainPanel.add(lbl_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 450));

        lbl_fields.setIcon(new ImageIcon("src/main/java/com/desarrollo/images/hamburguer.png"));
        mainPanel.add(lbl_fields, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 420, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nameFocusLost
        if (txt_name.getText().isEmpty()) {
            txt_name.setText(defaultName);
            txt_name.setForeground(new Color(204, 209, 209));
        }
    }//GEN-LAST:event_txt_nameFocusLost

    private void txt_nameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_nameMousePressed
        if (txt_name.getText().equals(defaultName)) {
            txt_name.setText("");
            txt_name.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_nameMousePressed

    private void txt_lastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_lastNameFocusLost
        if (txt_lastName.getText().isEmpty()) {
            txt_lastName.setText(defaultLastName);
            txt_lastName.setForeground(new Color(204, 209, 209));
        }
    }//GEN-LAST:event_txt_lastNameFocusLost

    private void txt_lastNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_lastNameMousePressed
        if (txt_lastName.getText().equals(defaultLastName)) {
            txt_lastName.setText("");
            txt_lastName.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_lastNameMousePressed

    private void txt_documentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_documentFocusLost
        if (txt_document.getText().isEmpty()) {
            txt_document.setText(defaultDocument);
            txt_document.setForeground(new Color(204, 209, 209));
        }
    }//GEN-LAST:event_txt_documentFocusLost

    private void txt_documentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_documentMousePressed
        if (txt_document.getText().equals(defaultDocument)) {
            txt_document.setText("");
            txt_document.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_documentMousePressed

    private void txt_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emailFocusLost
        if (txt_email.getText().isEmpty()) {
            txt_email.setText(defaultEmail);
            txt_email.setForeground(new Color(204, 209, 209));
        }
    }//GEN-LAST:event_txt_emailFocusLost

    private void txt_emailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_emailMousePressed
        if (txt_email.getText().equals(defaultEmail)) {
            txt_email.setText("");
            txt_email.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_emailMousePressed

    private void pwd_confirmPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwd_confirmPasswordFocusLost
        if (String.valueOf(pwd_confirmPassword.getPassword()).isEmpty() /*&&!pwd_confirmPassword.isFocusOwner()*/) {
            pwd_confirmPassword.setText(defaultConfirmPassword);
            pwd_confirmPassword.setForeground(new Color(204, 209, 209));
        }
    }//GEN-LAST:event_pwd_confirmPasswordFocusLost

    private void pwd_confirmPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwd_confirmPasswordMousePressed
        if (String.valueOf(pwd_confirmPassword.getPassword()).equals(defaultConfirmPassword)) {
            pwd_confirmPassword.setText("");
            pwd_confirmPassword.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_pwd_confirmPasswordMousePressed

    private void pwd_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwd_passwordFocusLost
        if (String.valueOf(pwd_password.getPassword()).isEmpty()) {
            pwd_password.setText(defaultPassword);
            pwd_password.setForeground(new Color(204, 209, 209));
        }
    }//GEN-LAST:event_pwd_passwordFocusLost

    private void pwd_passwordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwd_passwordMousePressed
        if (String.valueOf(pwd_password.getPassword()).equals(defaultPassword)) {
            pwd_password.setText("");
            pwd_password.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_pwd_passwordMousePressed

    private void cbx_cityItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_cityItemStateChanged
        if (cbx_city.getSelectedIndex() == 0) {
            cbx_city.setForeground(new Color(204, 209, 209));
        } else {
            cbx_city.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_cbx_cityItemStateChanged

    private void btn_signInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_signInMouseEntered
        btn_signIn.setBackground(new Color(203, 67, 53));
    }//GEN-LAST:event_btn_signInMouseEntered

    private void btn_signInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_signInMouseExited
        btn_signIn.setBackground(new Color(231, 76, 60));
    }//GEN-LAST:event_btn_signInMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_signIn;
    private javax.swing.JComboBox<String> cbx_city;
    private javax.swing.JCheckBox chx_acceptConditions;
    private javax.swing.JCheckBox chx_wantInformation;
    private javax.swing.JLabel lbl_fields;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JLabel lbl_viewPassword1;
    private javax.swing.JLabel lbl_viewPassword2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPasswordField pwd_confirmPassword;
    private javax.swing.JPasswordField pwd_password;
    private javax.swing.JTextField txt_document;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_lastName;
    private javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables
}
