/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.desarrollo.registro;

import com.desarrollo.datos.Conexion;
import com.desarrollo.login.IniciarSesion;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Bryan Andagoya
 */
public class Registro extends javax.swing.JFrame {

    Conexion conexion = new Conexion();
    String path;

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public ImageIcon redimensionarImagen(String imgPath) {
        ImageIcon imagen = new ImageIcon(imgPath);

        Image redimensionarImg = imagen.getImage()
                .getScaledInstance(jLabelImagen.getWidth(), jLabelImagen.getHeight(), Image.SCALE_SMOOTH);

        ImageIcon imagenRedimensionada = new ImageIcon(redimensionarImg);

        return imagenRedimensionada;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JLMinimizar = new javax.swing.JLabel();
        jLCerrar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtNombres = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jBntCancelar = new javax.swing.JButton();
        jBtnRegistrar = new javax.swing.JButton();
        jLabelIniciarSesion = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxtApellidos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtUsuario = new javax.swing.JTextField();
        jConfirmPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelImagen = new javax.swing.JLabel();
        jBntCargarImagen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(46, 204, 113));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro");

        JLMinimizar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JLMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        JLMinimizar.setText("-");
        JLMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JLMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLMinimizarMouseClicked(evt);
            }
        });

        jLCerrar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLCerrar.setForeground(new java.awt.Color(255, 255, 255));
        jLCerrar.setText("X");
        jLCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JLMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(34, 49, 63));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombres:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jTxtNombres.setBackground(new java.awt.Color(108, 122, 137));
        jTxtNombres.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTxtNombres.setForeground(new java.awt.Color(245, 215, 110));
        jPanel3.add(jTxtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 320, 37));

        jPassword.setBackground(new java.awt.Color(108, 122, 137));
        jPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPassword.setForeground(new java.awt.Color(245, 215, 110));
        jPanel3.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 320, 35));

        jBntCancelar.setBackground(new java.awt.Color(240, 52, 52));
        jBntCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBntCancelar.setText("Cancelar");
        jPanel3.add(jBntCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, -1, -1));

        jBtnRegistrar.setBackground(new java.awt.Color(65, 131, 215));
        jBtnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBtnRegistrar.setText("Registrar");
        jBtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegistrarActionPerformed(evt);
            }
        });
        jPanel3.add(jBtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, -1, -1));

        jLabelIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIniciarSesion.setText("Ya tienes una cuenta? Iniciar sesión aquí");
        jLabelIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIniciarSesionMouseClicked(evt);
            }
        });
        jPanel3.add(jLabelIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, 360, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellidos:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jTxtApellidos.setBackground(new java.awt.Color(108, 122, 137));
        jTxtApellidos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTxtApellidos.setForeground(new java.awt.Color(245, 215, 110));
        jPanel3.add(jTxtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 320, 37));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Usuario:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jTxtUsuario.setBackground(new java.awt.Color(108, 122, 137));
        jTxtUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTxtUsuario.setForeground(new java.awt.Color(245, 215, 110));
        jPanel3.add(jTxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 320, 37));

        jConfirmPassword.setBackground(new java.awt.Color(108, 122, 137));
        jConfirmPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jConfirmPassword.setForeground(new java.awt.Color(245, 215, 110));
        jPanel3.add(jConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 250, 35));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fotografía:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 100, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Confirmar contraseña:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 200, 40));

        jLabelImagen.setBackground(new java.awt.Color(108, 122, 137));
        jLabelImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImagen.setOpaque(true);
        jPanel3.add(jLabelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 320, 230));

        jBntCargarImagen.setBackground(new java.awt.Color(204, 255, 204));
        jBntCargarImagen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBntCargarImagen.setText("Cargar");
        jBntCargarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBntCargarImagenActionPerformed(evt);
            }
        });
        jPanel3.add(jBntCargarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JLMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLMinimizarMouseClicked
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_JLMinimizarMouseClicked

    private void jLCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLCerrarMouseClicked

    private void jLabelIniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIniciarSesionMouseClicked
        IniciarSesion iniciar = new IniciarSesion();
        iniciar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelIniciarSesionMouseClicked

    private void jBntCargarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBntCargarImagenActionPerformed
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));

        FileNameExtensionFilter fileFilter
                = new FileNameExtensionFilter("*.Images", "jpg", "png", "gif");

        file.addChoosableFileFilter(fileFilter);

        //botón de selección
        int fileState = file.showSaveDialog(null);

        //si selecciona la imagen
        if (fileState == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            path = selectedFile.getAbsolutePath();

            //mostrar imagen en el label
//            jLabelImagen.setIcon(new ImageIcon(path));
            jLabelImagen.setIcon(redimensionarImagen(path));

        } else if (fileState == JFileChooser.CANCEL_OPTION) {
            System.out.println("No se ha seleccionado ninguna imagen");
        }
    }//GEN-LAST:event_jBntCargarImagenActionPerformed

    private void jBtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegistrarActionPerformed
        try {
            //1. Establecer conexión
            Connection conn = conexion.getConnection();
            //2. Crear objeto para preparar queries -> PreparedStatement
            PreparedStatement stmt = conn
                    .prepareStatement("INSERT INTO usuarios (nombres, apellidos, usuario, contraseña, imagen) VALUES (?,?,?,?,?)");

            stmt.setString(1, jTxtNombres.getText());
            stmt.setString(2, jTxtApellidos.getText());
            stmt.setString(3, jTxtUsuario.getText());
            stmt.setString(4, String.valueOf(jPassword.getPassword()));

            //capturar imagen en binario
            InputStream img = new FileInputStream(new File(path));
            stmt.setBlob(5, img);

            //ejecutar query
            if (stmt.executeUpdate() != 0) { //devuelve un valor de tipo entero -> 0 si no se insertó -> distinto de 0 si se insertó
                JOptionPane.showMessageDialog(null, "Registro con éxito");
            } else {
                JOptionPane.showMessageDialog(null, "Error al registrar");
            }

            //cerrar objetos de conexión
            stmt.close();
            conn.close();
        } catch (SQLException | FileNotFoundException ex) {
            ex.printStackTrace(System.out);
        }

    }//GEN-LAST:event_jBtnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Registro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLMinimizar;
    private javax.swing.JButton jBntCancelar;
    private javax.swing.JButton jBntCargarImagen;
    private javax.swing.JButton jBtnRegistrar;
    private javax.swing.JPasswordField jConfirmPassword;
    private javax.swing.JLabel jLCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelIniciarSesion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTxtApellidos;
    private javax.swing.JTextField jTxtNombres;
    private javax.swing.JTextField jTxtUsuario;
    // End of variables declaration//GEN-END:variables
}
