/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.desarrollo.t8_jframecalculadora;

import java.util.*;
import javax.swing.*;

/**
 *
 * @author Bryan Andagoya
 */
public class Calculadora extends javax.swing.JFrame {

    //Variables
    double num1;
    double num2;
    char operador;
    double resultadoOperacion;
    int contadorNumeros = 0;

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pantalla = new javax.swing.JTextField();
        division = new javax.swing.JButton();
        multiplicacion = new javax.swing.JButton();
        resta = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        siete = new javax.swing.JButton();
        ocho = new javax.swing.JButton();
        nueve = new javax.swing.JButton();
        suma = new javax.swing.JButton();
        cuatro = new javax.swing.JButton();
        cinco = new javax.swing.JButton();
        seis = new javax.swing.JButton();
        resultado = new javax.swing.JButton();
        uno = new javax.swing.JButton();
        dos = new javax.swing.JButton();
        tres = new javax.swing.JButton();
        cero = new javax.swing.JButton();
        punto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pantalla.setBackground(new java.awt.Color(204, 204, 255));
        pantalla.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pantalla.setForeground(new java.awt.Color(0, 0, 0));
        pantalla.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pantalla.setText("0");
        pantalla.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 3, true));
        pantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pantallaActionPerformed(evt);
            }
        });
        jPanel1.add(pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 6, 280, 42));

        division.setBackground(new java.awt.Color(204, 204, 204));
        division.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        division.setText("/");
        division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionActionPerformed(evt);
            }
        });
        jPanel1.add(division, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 60, 62));

        multiplicacion.setBackground(new java.awt.Color(204, 204, 204));
        multiplicacion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        multiplicacion.setText("*");
        multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicacionActionPerformed(evt);
            }
        });
        jPanel1.add(multiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 60, 61));

        resta.setBackground(new java.awt.Color(204, 204, 204));
        resta.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        resta.setText("-");
        resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaActionPerformed(evt);
            }
        });
        jPanel1.add(resta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 60, 61));

        limpiar.setBackground(new java.awt.Color(204, 204, 204));
        limpiar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        limpiar.setText("C");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        jPanel1.add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 60, 61));

        siete.setBackground(new java.awt.Color(204, 204, 204));
        siete.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        siete.setText("7");
        siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sieteActionPerformed(evt);
            }
        });
        jPanel1.add(siete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 60, 61));

        ocho.setBackground(new java.awt.Color(204, 204, 204));
        ocho.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ocho.setText("8");
        ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoActionPerformed(evt);
            }
        });
        jPanel1.add(ocho, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 60, 62));

        nueve.setBackground(new java.awt.Color(204, 204, 204));
        nueve.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nueve.setText("9");
        nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueveActionPerformed(evt);
            }
        });
        jPanel1.add(nueve, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 60, 61));

        suma.setBackground(new java.awt.Color(204, 204, 204));
        suma.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        suma.setText("+");
        suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaActionPerformed(evt);
            }
        });
        jPanel1.add(suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 161, 60, 140));

        cuatro.setBackground(new java.awt.Color(204, 204, 204));
        cuatro.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cuatro.setText("4");
        cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroActionPerformed(evt);
            }
        });
        jPanel1.add(cuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 60, 61));

        cinco.setBackground(new java.awt.Color(204, 204, 204));
        cinco.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cinco.setText("5");
        cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoActionPerformed(evt);
            }
        });
        jPanel1.add(cinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 60, 62));

        seis.setBackground(new java.awt.Color(204, 204, 204));
        seis.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        seis.setText("6");
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });
        jPanel1.add(seis, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 60, 61));

        resultado.setBackground(new java.awt.Color(204, 204, 204));
        resultado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        resultado.setText("=");
        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });
        jPanel1.add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 60, 140));

        uno.setBackground(new java.awt.Color(204, 204, 204));
        uno.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        uno.setText("1");
        uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoActionPerformed(evt);
            }
        });
        jPanel1.add(uno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 60, 61));

        dos.setBackground(new java.awt.Color(204, 204, 204));
        dos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        dos.setText("2");
        dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosActionPerformed(evt);
            }
        });
        jPanel1.add(dos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 60, 62));

        tres.setBackground(new java.awt.Color(204, 204, 204));
        tres.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tres.setText("3");
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });
        jPanel1.add(tres, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 60, 61));

        cero.setBackground(new java.awt.Color(204, 204, 204));
        cero.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cero.setText("0");
        cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroActionPerformed(evt);
            }
        });
        jPanel1.add(cero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 130, 61));

        punto.setBackground(new java.awt.Color(204, 204, 204));
        punto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        punto.setText(",");
        punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoActionPerformed(evt);
            }
        });
        jPanel1.add(punto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 60, 61));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pantallaActionPerformed

    private void multiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicacionActionPerformed
        num1 = Double.parseDouble(pantalla.getText());
        operador = '*';
        pantalla.setText("0");
    }//GEN-LAST:event_multiplicacionActionPerformed

    private void restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaActionPerformed
        num1 = Double.parseDouble(pantalla.getText());
        operador = '-';
        pantalla.setText("0");
    }//GEN-LAST:event_restaActionPerformed

    private void nueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueveActionPerformed
        if (pantalla.getText().equals("0")) {
            pantalla.setText(nueve.getText());
        } else {
            pantalla.setText(pantalla.getText() + nueve.getText());
        }
    }//GEN-LAST:event_nueveActionPerformed

    private void sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaActionPerformed
        num1 = Double.parseDouble(pantalla.getText().replace(',', '.'));
        operador = '+';
        pantalla.setText("0");
    }//GEN-LAST:event_sumaActionPerformed

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed
        if (pantalla.getText().equals("0")) {
            pantalla.setText(seis.getText());
        } else {
            pantalla.setText(pantalla.getText() + seis.getText());
        }
    }//GEN-LAST:event_seisActionPerformed

    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoActionPerformed
        num2 = Double.parseDouble(pantalla.getText().replace(',', '.'));

        switch (operador) {
            case '+':
                resultadoOperacion = num1 + num2;
                desplegarResultado();
                break;
            case '-':
                resultadoOperacion = num1 - num2;
                desplegarResultado();
                break;
            case '*':
                resultadoOperacion = num1 * num2;
                desplegarResultado();
                break;
            case '/':
                if (num1 == 0 && num2 == 0) {
                    pantalla.setText("Indeterminación");
                } else if (num2 == 0) {
                    pantalla.setText("No existe división para cero");
                } else {
                    resultadoOperacion = num1 / num2;
                    desplegarResultado();
                }
                break;
        }
    }//GEN-LAST:event_resultadoActionPerformed

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresActionPerformed
        if (pantalla.getText().equals("0")) {
            pantalla.setText(tres.getText());
        } else {
            pantalla.setText(pantalla.getText() + tres.getText());
        }
    }//GEN-LAST:event_tresActionPerformed

    private void sieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sieteActionPerformed
        //evento
        if (pantalla.getText().equals("0")) {
            pantalla.setText(siete.getText());
        } else {
            pantalla.setText(pantalla.getText() + siete.getText());
        }
    }//GEN-LAST:event_sieteActionPerformed

    private void puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoActionPerformed
        if (!pantalla.getText().contains(",")) {
            pantalla.setText(pantalla.getText() + punto.getText());
        }
    }//GEN-LAST:event_puntoActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        pantalla.setText("0");
    }//GEN-LAST:event_limpiarActionPerformed

    private void ochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoActionPerformed
        if (pantalla.getText().equals("0")) {
            pantalla.setText(ocho.getText());
        } else {
            pantalla.setText(pantalla.getText() + ocho.getText());
        }
    }//GEN-LAST:event_ochoActionPerformed

    private void cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroActionPerformed
        if (pantalla.getText().equals("0")) {
            pantalla.setText(cuatro.getText());
        } else {
            pantalla.setText(pantalla.getText() + cuatro.getText());
        }
    }//GEN-LAST:event_cuatroActionPerformed

    private void cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoActionPerformed
        if (pantalla.getText().equals("0")) {
            pantalla.setText(cinco.getText());
        } else {
            pantalla.setText(pantalla.getText() + cinco.getText());
        }
    }//GEN-LAST:event_cincoActionPerformed

    private void unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoActionPerformed
        if (pantalla.getText().equals("0")) {
            pantalla.setText(uno.getText());
        } else {
            pantalla.setText(pantalla.getText() + uno.getText());
        }
    }//GEN-LAST:event_unoActionPerformed

    private void dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosActionPerformed
//        if (pantalla.getText().equals("0")) {
//            pantalla.setText(dos.getText());
//        } else {
//            pantalla.setText(pantalla.getText() + dos.getText());
//        }
desplegarTextoPantalla(dos);
    }//GEN-LAST:event_dosActionPerformed

    private void ceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceroActionPerformed
//        if (pantalla.getText().equals("0")) {
//            pantalla.setText(cero.getText());
//        } else {
//            pantalla.setText(pantalla.getText() + cero.getText());
//        }
desplegarTextoPantalla(cero);
    }//GEN-LAST:event_ceroActionPerformed

    private void divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionActionPerformed
        num1 = Double.parseDouble(pantalla.getText());
        operador = '/';
        pantalla.setText("0");
    }//GEN-LAST:event_divisionActionPerformed

    public void desplegarResultado() {
//        if ((resultadoOperacion + "").endsWith(".0")) {
//            pantalla.setText(((int) resultadoOperacion + "").replace('.', ','));
//        } else {
//            pantalla.setText((resultadoOperacion + "").replace('.', ','));
//        }

        if ((resultadoOperacion + "").endsWith(".0")) {
            pantalla.setText((int) resultadoOperacion + "");
        } else {
            pantalla.setText((resultadoOperacion + "").replace('.', ','));
        }
    }

    public String enteroSinDecimal(double resultadoOperacion) {
        String numeroSinDecimal;
        numeroSinDecimal = resultadoOperacion + "";

        if (resultadoOperacion % 1 == 0) {
            numeroSinDecimal = numeroSinDecimal.substring(0, numeroSinDecimal.length() - 2);
        }

        return numeroSinDecimal;
    }

    public void desplegarTextoPantalla(JButton boton) {
        if (pantalla.getText().equals("0")) {
            pantalla.setText(cero.getText());
        } else {
            if (contadorNumeros == 4) {
                char[] aux = pantalla.getText().toCharArray();
                List textoPantalla = Arrays.asList(aux);
                textoPantalla.add('.', textoPantalla.size() - 3);
            }
            pantalla.setText(pantalla.getText() + boton.getText());
            if (contadorNumeros == 4) {
                contadorNumeros = 1;
            } else {
                contadorNumeros++;
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cero;
    private javax.swing.JButton cinco;
    private javax.swing.JButton cuatro;
    private javax.swing.JButton division;
    private javax.swing.JButton dos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton multiplicacion;
    private javax.swing.JButton nueve;
    private javax.swing.JButton ocho;
    private javax.swing.JTextField pantalla;
    private javax.swing.JButton punto;
    private javax.swing.JButton resta;
    private javax.swing.JButton resultado;
    private javax.swing.JButton seis;
    private javax.swing.JButton siete;
    private javax.swing.JButton suma;
    private javax.swing.JButton tres;
    private javax.swing.JButton uno;
    // End of variables declaration//GEN-END:variables
}
