/*
 * Calculadora - JFrame
 */
package com.desarrollo.calculadora;

import java.awt.*;
import java.awt.event.*;
import java.awt.geom.RoundRectangle2D;
import java.text.*;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author Bryan Andagoya
 */
public final class Calculator extends javax.swing.JFrame {

    //Variables
    private Double[] operands = {null, null};
    private final DecimalFormat mainScreenFormatter = new DecimalFormat("###,###.####################");
    private final DecimalFormat secondScreenFormatter = new DecimalFormat("#.####################");
    private final ArrayList<JButton> symbolButtons = new ArrayList<JButton>();
    private final ArrayList<JButton> numberButtons = new ArrayList<JButton>();

    private Point initialClick;
    private String operator = null;
    private boolean overwriteMainScreen = true;
    private boolean equalClicked = false;
    private Double result = null;
    private boolean firstTime = true;
    private boolean indeterminacy = false;
    private boolean divisionBy0 = false;
    private Double equalResult;
    private boolean overwriteSecondScreen = false;

    /**
     * Creates new form Calculadora
     */
    public Calculator() {
        initComponents();
        configureWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        btn_division = new javax.swing.JButton();
        btn_multiplication = new javax.swing.JButton();
        btn_subtraction = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_sqrt = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_equal = new javax.swing.JButton();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_comma = new javax.swing.JButton();
        btn_sum = new javax.swing.JButton();
        btn_pow = new javax.swing.JButton();
        pnl_TitleBar = new javax.swing.JPanel();
        btn_close = new javax.swing.JButton();
        btn_minimize = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txt_mainScreen = new javax.swing.JTextField();
        txt_secondScreen = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setMinimumSize(new java.awt.Dimension(350, 570));
        setUndecorated(true);
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(221, 253, 255));
        mainPanel.setMinimumSize(new java.awt.Dimension(350, 570));
        mainPanel.setPreferredSize(new java.awt.Dimension(350, 570));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_division.setBackground(new java.awt.Color(234, 254, 255));
        btn_division.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        btn_division.setForeground(new java.awt.Color(15, 70, 82));
        btn_division.setIcon(new ImageIcon("src/main/java/com/desarrollo/images/button.png"));
        btn_division.setText("/");
        btn_division.setContentAreaFilled(false);
        btn_division.setFocusPainted(false);
        btn_division.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_division.setRolloverIcon(new ImageIcon("src/main/java/com/desarrollo/images/button2.png"));
        btn_division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divisionActionPerformed(evt);
            }
        });
        mainPanel.add(btn_division, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 60, 60));

        btn_multiplication.setBackground(new java.awt.Color(234, 254, 255));
        btn_multiplication.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        btn_multiplication.setForeground(new java.awt.Color(15, 70, 82));
        btn_multiplication.setIcon(new ImageIcon("src/main/java/com/desarrollo/images/button.png"));
        btn_multiplication.setText("*");
        btn_multiplication.setContentAreaFilled(false);
        btn_multiplication.setFocusPainted(false);
        btn_multiplication.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_multiplication.setRolloverIcon(new ImageIcon("src/main/java/com/desarrollo/images/button2.png"));
        btn_multiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multiplicationActionPerformed(evt);
            }
        });
        mainPanel.add(btn_multiplication, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 60, 60));

        btn_subtraction.setBackground(new java.awt.Color(234, 254, 255));
        btn_subtraction.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        btn_subtraction.setForeground(new java.awt.Color(15, 70, 82));
        btn_subtraction.setIcon(new ImageIcon("src/main/java/com/desarrollo/images/button.png"));
        btn_subtraction.setText("-");
        btn_subtraction.setContentAreaFilled(false);
        btn_subtraction.setFocusPainted(false);
        btn_subtraction.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_subtraction.setRolloverIcon(new ImageIcon("src/main/java/com/desarrollo/images/button2.png"));
        btn_subtraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_subtractionActionPerformed(evt);
            }
        });
        mainPanel.add(btn_subtraction, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 60, 60));

        btn_clear.setBackground(new java.awt.Color(234, 254, 255));
        btn_clear.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(15, 70, 82));
        btn_clear.setIcon(new ImageIcon("src/main/java/com/desarrollo/images/buttonAC.png"));
        btn_clear.setText("AC");
        btn_clear.setContentAreaFilled(false);
        btn_clear.setFocusPainted(false);
        btn_clear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_clear.setRolloverIcon(new ImageIcon("src/main/java/com/desarrollo/images/buttonAC2.png"));
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        mainPanel.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 60, 60));

        btn_7.setBackground(new java.awt.Color(234, 254, 255));
        btn_7.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        btn_7.setForeground(new java.awt.Color(15, 70, 82));
        btn_7.setIcon(new ImageIcon("src/main/java/com/desarrollo/images/button3.png"));
        btn_7.setText("7");
        btn_7.setContentAreaFilled(false);
        btn_7.setFocusPainted(false);
        btn_7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_7.setMaximumSize(new java.awt.Dimension(39, 39));
        btn_7.setMinimumSize(new java.awt.Dimension(39, 39));
        btn_7.setPreferredSize(new java.awt.Dimension(39, 39));
        btn_7.setPressedIcon(new ImageIcon("src/main/java/com/desarrollo/images/button3.png"));
        btn_7.setRolloverIcon(new ImageIcon("src/main/java/com/desarrollo/images/button2.png"));
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });
        mainPanel.add(btn_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 60, 60));

        btn_8.setBackground(new java.awt.Color(234, 254, 255));
        btn_8.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        btn_8.setForeground(new java.awt.Color(15, 70, 82));
        btn_8.setIcon(new ImageIcon("src/main/java/com/desarrollo/images/button3.png"));
        btn_8.setText("8");
        btn_8.setContentAreaFilled(false);
        btn_8.setFocusPainted(false);
        btn_8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_8.setMaximumSize(new java.awt.Dimension(39, 39));
        btn_8.setMinimumSize(new java.awt.Dimension(39, 39));
        btn_8.setPressedIcon(new ImageIcon("src/main/java/com/desarrollo/images/button3.png"));
        btn_8.setRolloverIcon(new ImageIcon("src/main/java/com/desarrollo/images/button2.png"));
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });
        mainPanel.add(btn_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 60, 60));

        btn_9.setBackground(new java.awt.Color(234, 254, 255));
        btn_9.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        btn_9.setForeground(new java.awt.Color(15, 70, 82));
        btn_9.setIcon(new ImageIcon("src/main/java/com/desarrollo/images/button3.png"));
        btn_9.setText("9");
        btn_9.setContentAreaFilled(false);
        btn_9.setFocusPainted(false);
        btn_9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_9.setMaximumSize(new java.awt.Dimension(39, 39));
        btn_9.setMinimumSize(new java.awt.Dimension(39, 39));
        btn_9.setPressedIcon(new ImageIcon("src/main/java/com/desarrollo/images/button3.png"));
        btn_9.setRolloverIcon(new ImageIcon("src/main/java/com/desarrollo/images/button2.png"));
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });
        mainPanel.add(btn_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 60, 60));

        btn_sqrt.setBackground(new java.awt.Color(234, 254, 255));
        btn_sqrt.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        btn_sqrt.setForeground(new java.awt.Color(15, 70, 82));
        btn_sqrt.setIcon(new ImageIcon("src/main/java/com/desarrollo/images/button.png"));
        btn_sqrt.setText("√ ");
        btn_sqrt.setContentAreaFilled(false);
        btn_sqrt.setFocusPainted(false);
        btn_sqrt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_sqrt.setRolloverIcon(new ImageIcon("src/main/java/com/desarrollo/images/button2.png"));
        btn_sqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sqrtActionPerformed(evt);
            }
        });
        mainPanel.add(btn_sqrt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 60, 60));

        btn_4.setBackground(new java.awt.Color(234, 254, 255));
        btn_4.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        btn_4.setForeground(new java.awt.Color(15, 70, 82));
        btn_4.setIcon(new ImageIcon("src/main/java/com/desarrollo/images/button3.png"));
        btn_4.setText("4");
        btn_4.setContentAreaFilled(false);
        btn_4.setFocusPainted(false);
        btn_4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_4.setMaximumSize(new java.awt.Dimension(39, 39));
        btn_4.setMinimumSize(new java.awt.Dimension(39, 39));
        btn_4.setPressedIcon(new ImageIcon("src/main/java/com/desarrollo/images/button3.png"));
        btn_4.setRolloverIcon(new ImageIcon("src/main/java/com/desarrollo/images/button2.png"));
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });
        mainPanel.add(btn_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 60, 60));

        btn_5.setBackground(new java.awt.Color(234, 254, 255));
        btn_5.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        btn_5.setForeground(new java.awt.Color(15, 70, 82));
        btn_5.setIcon(new ImageIcon("src/main/java/com/desarrollo/images/button3.png"));
        btn_5.setText("5");
        btn_5.setContentAreaFilled(false);
        btn_5.setFocusPainted(false);
        btn_5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_5.setMaximumSize(new java.awt.Dimension(39, 39));
        btn_5.setMinimumSize(new java.awt.Dimension(39, 39));
        btn_5.setPressedIcon(new ImageIcon("src/main/java/com/desarrollo/images/button3.png"));
        btn_5.setRolloverIcon(new ImageIcon("src/main/java/com/desarrollo/images/button2.png"));
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });
        mainPanel.add(btn_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 60, 60));

        btn_6.setBackground(new java.awt.Color(234, 254, 255));
        btn_6.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        btn_6.setForeground(new java.awt.Color(15, 70, 82));
        btn_6.setIcon(new ImageIcon("src/main/java/com/desarrollo/images/button3.png"));
        btn_6.setText("6");
        btn_6.setContentAreaFilled(false);
        btn_6.setFocusPainted(false);
        btn_6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_6.setMaximumSize(new java.awt.Dimension(39, 39));
        btn_6.setMinimumSize(new java.awt.Dimension(39, 39));
        btn_6.setPressedIcon(new ImageIcon("src/main/java/com/desarrollo/images/button3.png"));
        btn_6.setRolloverIcon(new ImageIcon("src/main/java/com/desarrollo/images/button2.png"));
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });
        mainPanel.add(btn_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 60, 60));

        btn_equal.setBackground(new java.awt.Color(234, 254, 255));
        btn_equal.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        btn_equal.setForeground(new java.awt.Color(15, 70, 82));
        btn_equal.setIcon(new ImageIcon("src/main/java/com/desarrollo/images/button.png"));
        btn_equal.setText("=");
        btn_equal.setContentAreaFilled(false);
        btn_equal.setFocusPainted(false);
        btn_equal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_equal.setRolloverIcon(new ImageIcon("src/main/java/com/desarrollo/images/button2.png"));
        btn_equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_equalActionPerformed(evt);
            }
        });
        mainPanel.add(btn_equal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 60, 60));

        btn_1.setBackground(new java.awt.Color(234, 254, 255));
        btn_1.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        btn_1.setForeground(new java.awt.Color(15, 70, 82));
        btn_1.setIcon(new ImageIcon("src/main/java/com/desarrollo/images/button3.png"));
        btn_1.setText("1");
        btn_1.setContentAreaFilled(false);
        btn_1.setFocusPainted(false);
        btn_1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_1.setMaximumSize(new java.awt.Dimension(39, 39));
        btn_1.setMinimumSize(new java.awt.Dimension(39, 39));
        btn_1.setPressedIcon(new ImageIcon("src/main/java/com/desarrollo/images/button3.png"));
        btn_1.setRolloverIcon(new ImageIcon("src/main/java/com/desarrollo/images/button2.png"));
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });
        mainPanel.add(btn_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 60, 60));

        btn_2.setBackground(new java.awt.Color(234, 254, 255));
        btn_2.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        btn_2.setForeground(new java.awt.Color(15, 70, 82));
        btn_2.setIcon(new ImageIcon("src/main/java/com/desarrollo/images/button3.png"));
        btn_2.setText("2");
        btn_2.setContentAreaFilled(false);
        btn_2.setFocusPainted(false);
        btn_2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_2.setMaximumSize(new java.awt.Dimension(39, 39));
        btn_2.setMinimumSize(new java.awt.Dimension(39, 39));
        btn_2.setPressedIcon(new ImageIcon("src/main/java/com/desarrollo/images/button3.png"));
        btn_2.setRolloverIcon(new ImageIcon("src/main/java/com/desarrollo/images/button2.png"));
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });
        mainPanel.add(btn_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 60, 60));

        btn_3.setBackground(new java.awt.Color(234, 254, 255));
        btn_3.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        btn_3.setForeground(new java.awt.Color(15, 70, 82));
        btn_3.setIcon(new ImageIcon("src/main/java/com/desarrollo/images/button3.png"));
        btn_3.setText("3");
        btn_3.setContentAreaFilled(false);
        btn_3.setFocusPainted(false);
        btn_3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_3.setMaximumSize(new java.awt.Dimension(39, 39));
        btn_3.setMinimumSize(new java.awt.Dimension(39, 39));
        btn_3.setPressedIcon(new ImageIcon("src/main/java/com/desarrollo/images/button3.png"));
        btn_3.setRolloverIcon(new ImageIcon("src/main/java/com/desarrollo/images/button2.png"));
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });
        mainPanel.add(btn_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 60, 60));

        btn_0.setBackground(new java.awt.Color(234, 254, 255));
        btn_0.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        btn_0.setForeground(new java.awt.Color(15, 70, 82));
        btn_0.setIcon(null);
        btn_0.setText("0");
        btn_0.setContentAreaFilled(false);
        btn_0.setFocusPainted(false);
        btn_0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_0.setMaximumSize(new java.awt.Dimension(39, 39));
        btn_0.setMinimumSize(new java.awt.Dimension(39, 39));
        btn_0.setPressedIcon(new ImageIcon("src/main/java/com/desarrollo/images/button3.png"));
        btn_0.setRolloverIcon(new ImageIcon("src/main/java/com/desarrollo/images/button2.png"));
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });
        mainPanel.add(btn_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 60, 60));

        btn_comma.setBackground(new java.awt.Color(234, 254, 255));
        btn_comma.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        btn_comma.setForeground(new java.awt.Color(15, 70, 82));
        btn_comma.setIcon(new ImageIcon("src/main/java/com/desarrollo/images/button3.png"));
        btn_comma.setText(",");
        btn_comma.setContentAreaFilled(false);
        btn_comma.setFocusPainted(false);
        btn_comma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_comma.setMaximumSize(new java.awt.Dimension(39, 39));
        btn_comma.setMinimumSize(new java.awt.Dimension(39, 39));
        btn_comma.setPressedIcon(new ImageIcon("src/main/java/com/desarrollo/images/button3.png"));
        btn_comma.setRolloverIcon(new ImageIcon("src/main/java/com/desarrollo/images/button2.png"));
        btn_comma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_commaActionPerformed(evt);
            }
        });
        mainPanel.add(btn_comma, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 60, 60));

        btn_sum.setBackground(new java.awt.Color(234, 254, 255));
        btn_sum.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        btn_sum.setForeground(new java.awt.Color(15, 70, 82));
        btn_sum.setIcon(new ImageIcon("src/main/java/com/desarrollo/images/button.png"));
        btn_sum.setText("+");
        btn_sum.setContentAreaFilled(false);
        btn_sum.setFocusPainted(false);
        btn_sum.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_sum.setRolloverIcon(new ImageIcon("src/main/java/com/desarrollo/images/button2.png"));
        btn_sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumActionPerformed(evt);
            }
        });
        mainPanel.add(btn_sum, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 60, 60));

        btn_pow.setBackground(new java.awt.Color(234, 254, 255));
        btn_pow.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        btn_pow.setForeground(new java.awt.Color(15, 70, 82));
        btn_pow.setIcon(new ImageIcon("src/main/java/com/desarrollo/images/button.png"));
        btn_pow.setText("^");
        btn_pow.setContentAreaFilled(false);
        btn_pow.setFocusPainted(false);
        btn_pow.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_pow.setRolloverIcon(new ImageIcon("src/main/java/com/desarrollo/images/button2.png"));
        btn_pow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_powActionPerformed(evt);
            }
        });
        mainPanel.add(btn_pow, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 60, 60));

        pnl_TitleBar.setBackground(new java.awt.Color(221, 253, 255));
        pnl_TitleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_TitleBarMouseDragged(evt);
            }
        });
        pnl_TitleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_TitleBarMousePressed(evt);
            }
        });

        btn_close.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        btn_close.setForeground(new java.awt.Color(255, 149, 5));
        btn_close.setIcon(new ImageIcon("src/main/java/com/desarrollo/images/close.png"));
        btn_close.setBorder(null);
        btn_close.setBorderPainted(false);
        btn_close.setContentAreaFilled(false);
        btn_close.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_close.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        btn_minimize.setIcon(new ImageIcon("src/main/java/com/desarrollo/images/minimize.png"));
        btn_minimize.setBorder(null);
        btn_minimize.setBorderPainted(false);
        btn_minimize.setContentAreaFilled(false);
        btn_minimize.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_minimize.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_minimizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_TitleBarLayout = new javax.swing.GroupLayout(pnl_TitleBar);
        pnl_TitleBar.setLayout(pnl_TitleBarLayout);
        pnl_TitleBarLayout.setHorizontalGroup(
            pnl_TitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_TitleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(298, Short.MAX_VALUE))
        );
        pnl_TitleBarLayout.setVerticalGroup(
            pnl_TitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TitleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_TitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        mainPanel.add(pnl_TitleBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 30));

        jPanel1.setBackground(new java.awt.Color(244, 254, 255));

        txt_mainScreen.setEditable(false);
        txt_mainScreen.setBackground(new java.awt.Color(244, 254, 255));
        txt_mainScreen.setFont(new java.awt.Font("Cambria Math", 1, 28)); // NOI18N
        txt_mainScreen.setForeground(new java.awt.Color(35, 116, 140));
        txt_mainScreen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_mainScreen.setText("0");
        txt_mainScreen.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 15));
        txt_mainScreen.setMaximumSize(new java.awt.Dimension(244, 48));
        txt_mainScreen.setMinimumSize(new java.awt.Dimension(244, 48));
        txt_mainScreen.setPreferredSize(new java.awt.Dimension(244, 48));
        txt_mainScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mainScreenActionPerformed(evt);
            }
        });

        txt_secondScreen.setEditable(false);
        txt_secondScreen.setBackground(new java.awt.Color(244, 254, 255));
        txt_secondScreen.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        txt_secondScreen.setForeground(new java.awt.Color(139, 193, 209));
        txt_secondScreen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_secondScreen.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 15));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_mainScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_secondScreen)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txt_secondScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_mainScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 38, 350, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 344, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 537, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_mainScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mainScreenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mainScreenActionPerformed

    private void btn_multiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multiplicationActionPerformed
        performOperation(btn_multiplication);
    }//GEN-LAST:event_btn_multiplicationActionPerformed

    private void btn_subtractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_subtractionActionPerformed
        performOperation(btn_subtraction);
        btn_subtraction.setEnabled(false);
    }//GEN-LAST:event_btn_subtractionActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
        writeOnScreen(btn_9);
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_sqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sqrtActionPerformed
        calculateSqrt();
    }//GEN-LAST:event_btn_sqrtActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        writeOnScreen(btn_6);
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_equalActionPerformed
        showResult();

        if (equalClicked) {
            if (equalResult != null) {

                txt_secondScreen.setText(secondScreenFormatter.format(equalResult)
                        + " "
                        + operator
                        + " "
                        + secondScreenFormatter.format(operands[1])
                        + " "
                        + btn_equal.getText());

            }

        } else {
            if (!txt_secondScreen.getText().contains("=")) {

                txt_secondScreen.setText(txt_secondScreen.getText()
                        + " "
                        + btn_equal.getText());

            }
        }

        equalResult = operands[0];
        overwriteSecondScreen = true;

        equalClicked = true;
    }//GEN-LAST:event_btn_equalActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        writeOnScreen(btn_3);
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        writeOnScreen(btn_7);
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_commaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_commaActionPerformed
        if (!txt_mainScreen.getText().contains(",") && !overwriteMainScreen) {
            txt_mainScreen.setText(txt_mainScreen.getText() + btn_comma.getText());

            txt_secondScreen.setText(txt_secondScreen.getText()
                    + btn_comma.getText());
        }
    }//GEN-LAST:event_btn_commaActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        if (btn_equal.isEnabled()) {
            enableSymbolButtons(false);
        }

        if (!btn_0.isEnabled()) {
            enableNumberButtons(true);
        }

        for (int i = 0; i < operands.length; i++) {
            operands[i] = null;
        }

        txt_mainScreen.setText("0");
        txt_secondScreen.setText("");
        operator = null;
        equalClicked = false;
        firstTime = true;
        indeterminacy = false;
        divisionBy0 = false;
        overwriteMainScreen = true;
        btn_subtraction.setEnabled(true);
        equalResult = null;
        result = null;
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        writeOnScreen(btn_8);
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        writeOnScreen(btn_4);
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        writeOnScreen(btn_5);
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        writeOnScreen(btn_1);
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        writeOnScreen(btn_2);
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
        writeOnScreen(btn_0);
    }//GEN-LAST:event_btn_0ActionPerformed

    private void btn_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divisionActionPerformed
        performOperation(btn_division);
    }//GEN-LAST:event_btn_divisionActionPerformed

    private void btn_sumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumActionPerformed
        performOperation(btn_sum);
    }//GEN-LAST:event_btn_sumActionPerformed

    private void btn_powActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_powActionPerformed
        performOperation(btn_pow);
    }//GEN-LAST:event_btn_powActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_minimizeActionPerformed
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btn_minimizeActionPerformed

    private void pnl_TitleBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_TitleBarMouseDragged
        // get location of Window
        int thisX = getLocation().x;
        int thisY = getLocation().y;

        // Determine how much the mouse moved since the initial click
        int xMoved = evt.getX() - initialClick.x;
        int yMoved = evt.getY() - initialClick.y;

        // Move window to this position
        int X = thisX + xMoved;
        int Y = thisY + yMoved;
        setLocation(X, Y);
    }//GEN-LAST:event_pnl_TitleBarMouseDragged

    private void pnl_TitleBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_TitleBarMousePressed
        initialClick = evt.getPoint();
    }//GEN-LAST:event_pnl_TitleBarMousePressed

    public void configureWindow() {
        setLocationRelativeTo(null);
        fillSymbolButtonsList();
        fillNumberButtonsList();
        enableSymbolButtons(false);
        btn_subtraction.setEnabled(true);

        setIconImage(Toolkit.getDefaultToolkit()
                .getImage("src/main/java/com/desarrollo/images/icon.png"));

        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                setShape(new RoundRectangle2D.Double(
                        0, 0, getWidth(), getHeight(), 20, 20));
            }
        });
    }

    /**
     * Method that fills the lockable buttons list.
     */
    public void fillSymbolButtonsList() {
        symbolButtons.add(btn_sum);
        symbolButtons.add(btn_subtraction);
        symbolButtons.add(btn_multiplication);
        symbolButtons.add(btn_division);
        symbolButtons.add(btn_pow);
        symbolButtons.add(btn_sqrt);
        symbolButtons.add(btn_comma);
        symbolButtons.add(btn_equal);
    }

    public void fillNumberButtonsList() {
        numberButtons.add(btn_0);
        numberButtons.add(btn_1);
        numberButtons.add(btn_2);
        numberButtons.add(btn_3);
        numberButtons.add(btn_4);
        numberButtons.add(btn_5);
        numberButtons.add(btn_6);
        numberButtons.add(btn_7);
        numberButtons.add(btn_8);
        numberButtons.add(btn_9);
    }

    /**
     * Method that enebles or disables the lockable buttons.
     *
     * @param enable Set true for enable the buttons.
     */
    public void enableSymbolButtons(boolean enable) {
        symbolButtons.forEach(button -> {
            button.setEnabled(enable);
        });
    }

    public void enableNumberButtons(boolean enable) {
        numberButtons.forEach(button -> {
            button.setEnabled(enable);
        });
    }

    /**
     * Method that formats the number.
     *
     * @param number The double number.
     * @return The formatted double number.
     */
    public String formatNumber(double number) {
        String aux = number + "";

        if (aux.endsWith(".0")) {
            return mainScreenFormatter.format((int) number);
        } else {
            return mainScreenFormatter.format(number);
        }
    }

    /**
     * Method that writes the numbers on the screen.
     *
     * @param button The number button.
     */
    public void writeOnScreen(JButton button) {
        double screenNumber;

        if (overwriteSecondScreen) {
            txt_secondScreen.setText(button.getText());
            overwriteSecondScreen = false;
        } else {
            txt_secondScreen.setText(txt_secondScreen.getText() + button.getText());
        }

        try {
            if (overwriteMainScreen) {
                screenNumber = mainScreenFormatter.parse(button.getText())
                        .doubleValue();

                if (equalClicked) {
                    for (int i = 0; i < operands.length; i++) {
                        operands[i] = null;
                    }
                    equalClicked = false;
                }

                txt_mainScreen.setText(mainScreenFormatter.format(screenNumber));
                overwriteMainScreen = false;
            } else {
                if (txt_mainScreen.getText().contains(",")) {
                    txt_mainScreen.setText(txt_mainScreen.getText() + button.getText());
                } else {
                    screenNumber = mainScreenFormatter.parse(txt_mainScreen.getText()
                            + button.getText()).doubleValue();
                    txt_mainScreen.setText(mainScreenFormatter.format(screenNumber));
                }
            }

            if (!btn_equal.isEnabled()) {
                symbolButtons.forEach(b -> {
                    b.setEnabled(true);
                });
            }

        } catch (ParseException ex) {
            txt_mainScreen.setText("Error");
            overwriteMainScreen = true;
        }

    }

    /**
     * Method that shows the result on the screen.
     */
    public void showResult() {

        if (operands[1] == null) {
            try {
                operands[1] = mainScreenFormatter.parse(txt_mainScreen.getText())
                        .doubleValue();

            } catch (ParseException ex) {
                txt_mainScreen.setText("Error");
                overwriteMainScreen = true;
            }
        }

        if (operands[0] != null && operands[1] != null) {
            if (operator.equals(btn_sum.getText())) {
                result = operands[0] + operands[1];
            } else if (operator.equals(btn_subtraction.getText())) {
                result = operands[0] - operands[1];
            } else if (operator.equals(btn_multiplication.getText())) {
                result = operands[0] * operands[1];
            } else if (operator.equals(btn_division.getText())) {
                if (operands[0] == 0 && operands[1] == 0) {
                    indeterminacy = true;
                } else if (operands[1] == 0) {
                    divisionBy0 = true;
                } else {
                    result = operands[0] / operands[1];
                }
            } else if (operator.equals(btn_pow.getText())) {
                result = Math.pow(operands[0], operands[1]);
            }

            if (indeterminacy) {
                txt_mainScreen.setText("Indeterminación");

                for (int i = 0; i < operands.length; i++) {
                    operands[i] = null;
                }

                enableSymbolButtons(false);
                enableNumberButtons(false);
                indeterminacy = false;
                overwriteSecondScreen = true;
            } else if (divisionBy0) {
                txt_mainScreen.setText("No existe división para 0");

                for (int i = 0; i < operands.length; i++) {
                    operands[i] = null;
                }

                enableSymbolButtons(false);
                enableNumberButtons(false);
                divisionBy0 = false;
                overwriteSecondScreen = true;
            } else {
                txt_mainScreen.setText(formatNumber(result));
                operands[0] = result;
            }

            overwriteMainScreen = true;
        } else {
            try {
                result = mainScreenFormatter.parse(txt_mainScreen.getText())
                        .doubleValue();

            } catch (ParseException ex) {
                txt_mainScreen.setText("Error");
                overwriteMainScreen = true;
            }
        }

    }

    /**
     * Method that performs the operations.
     *
     * @param operatorButton The operator button.
     */
    public void performOperation(JButton operatorButton) {

        if (overwriteSecondScreen) {
            if (result == null) {
                txt_secondScreen.setText(operatorButton.getText());
            } else {
                txt_secondScreen.setText(secondScreenFormatter.format(result)
                        + " " + operatorButton.getText() + " ");
            }

            overwriteSecondScreen = false;
        } else {
            txt_secondScreen.setText(txt_secondScreen.getText()
                    + " " + operatorButton.getText() + " ");
        }

        if (firstTime) {
            operator = operatorButton.getText();
            firstTime = false;
        }

        if (equalClicked) {
            for (int i = 0; i < operands.length; i++) {
                operands[i] = null;
            }
            equalClicked = false;
        }

        symbolButtons.forEach(button -> {
            button.setEnabled(false);
        });

        try {
            if (operands[0] == null) {
                operands[0] = mainScreenFormatter.parse(txt_mainScreen.getText()).doubleValue();
                overwriteMainScreen = true;
            } else {
                showResult();
            }
        } catch (ParseException ex) {
            txt_mainScreen.setText("Error");
            overwriteMainScreen = true;
        }

        operands[1] = null;
        operator = operatorButton.getText();
    }

    /**
     * Method that calculates the sqrt of a number.
     */
    public void calculateSqrt() {
        try {
            operands[0] = mainScreenFormatter.parse(txt_mainScreen.getText()).doubleValue();
            txt_secondScreen.setText("√" + secondScreenFormatter.format(operands[0]));
        } catch (ParseException ex) {
            txt_mainScreen.setText("Error");
            overwriteMainScreen = true;
        }

        if (operands[0] > 0) {
            result = Math.sqrt(operands[0]);
            txt_mainScreen.setText(formatNumber(result));
        } else {
            txt_mainScreen.setText("No existe raíz de un # -");
            enableSymbolButtons(false);
            enableNumberButtons(false);
        }

        for (int i = 0; i < operands.length; i++) {
            operands[i] = null;
        }

        overwriteMainScreen = true;
        overwriteSecondScreen = true;
    }

    /**
     * Main method.
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Calculator().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_comma;
    private javax.swing.JButton btn_division;
    private javax.swing.JButton btn_equal;
    private javax.swing.JButton btn_minimize;
    private javax.swing.JButton btn_multiplication;
    private javax.swing.JButton btn_pow;
    private javax.swing.JButton btn_sqrt;
    private javax.swing.JButton btn_subtraction;
    private javax.swing.JButton btn_sum;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pnl_TitleBar;
    private javax.swing.JTextField txt_mainScreen;
    private javax.swing.JTextField txt_secondScreen;
    // End of variables declaration//GEN-END:variables
}
