package ui;

import data.*;
import javax.swing.*;
import domain.Manager;
import domain.RawMaterial;
import domain.Supplier;
import java.util.*;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import ui.components.Icons;

public class ContactSupplier extends javax.swing.JFrame {

    //clase padre
    Inventory inventory;

    List<Supplier> suppliers = new ArrayList();
    List<RawMaterial> rawMaterials = new ArrayList();
    RawMaterialDAO rawMaterialDAO;
    SupplierDAO supplierDAO;
    Connection conexionTransaccional = null;
    public static Manager manager;

    public ContactSupplier() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        //this.rawMaterials = rawMaterials;
        try {
            insertItems();
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCBRawMaterial = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSpRawMaterialQuantity = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        jBOrder = new javax.swing.JButton();
        jBtnBack = new javax.swing.JButton();
        jLSupplierName = new javax.swing.JLabel();
        jLPhone = new javax.swing.JLabel();
        jLEmail = new javax.swing.JLabel();
        jLDescription = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ITSQMET BURGER");
        setIconImage(Icons.FRAME_ICON.getImage());

        jPanel1.setBackground(new java.awt.Color(238, 166, 94));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SOLICITUD DE PRODUCTOS");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Producto:");

        jCBRawMaterial.setBackground(new java.awt.Color(255, 103, 87));
        jCBRawMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCBRawMaterialMouseClicked(evt);
            }
        });
        jCBRawMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBRawMaterialActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Proveedor");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Teléfono:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre:");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Correo:");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cantidad:");

        jSpRawMaterialQuantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, 200, 1));

        jSeparator1.setBackground(new java.awt.Color(255, 103, 87));

        jBOrder.setBackground(new java.awt.Color(255, 103, 87));
        jBOrder.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBOrder.setForeground(new java.awt.Color(255, 255, 255));
        jBOrder.setIcon(new ImageIcon("src/main/java/ui/resources/images/Order.png"));
        jBOrder.setText("REALIZAR PEDIDO");
        jBOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOrderActionPerformed(evt);
            }
        });

        jBtnBack.setBackground(new java.awt.Color(255, 103, 87));
        jBtnBack.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBtnBack.setForeground(new java.awt.Color(255, 255, 255));
        jBtnBack.setIcon(new ImageIcon("src/main/java/ui/resources/images/Exit.png"));
        jBtnBack.setText("VOLVER");
        jBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackActionPerformed(evt);
            }
        });

        jLSupplierName.setForeground(new java.awt.Color(255, 255, 255));
        jLSupplierName.setText("nombre");

        jLPhone.setForeground(new java.awt.Color(255, 255, 255));
        jLPhone.setText("teléfono");

        jLEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLEmail.setText("email");

        jLDescription.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLDescription.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel7))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                                    .addComponent(jLEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jBtnBack)
                                        .addGap(133, 133, 133)
                                        .addComponent(jBOrder))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBRawMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpRawMaterialQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jCBRawMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jSpRawMaterialQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLDescription))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLSupplierName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLEmail))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBOrder)
                    .addComponent(jBtnBack))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBRawMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBRawMaterialActionPerformed
        try {
            for (RawMaterial rawMaterial : rawMaterials) {
                if (jCBRawMaterial.getSelectedItem().equals(rawMaterial.getName())) {
                    jLDescription.setText(rawMaterial.getDescription());
                }
            }
            showSupplier();
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
        }


    }//GEN-LAST:event_jCBRawMaterialActionPerformed

    private void jBOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOrderActionPerformed

        if (jCBRawMaterial.getSelectedIndex() != 0 && (int) jSpRawMaterialQuantity.getValue() > 0) {
            int cant = (int) jSpRawMaterialQuantity.getValue();
            for (RawMaterial rawMaterial : rawMaterials) {
                if (jCBRawMaterial.getSelectedItem().equals(rawMaterial.getName())) {
                    System.out.println(jCBRawMaterial.getSelectedItem());
                    cant += rawMaterial.getQuantity();
                    System.out.println(cant + rawMaterial.getId());
                    rawMaterial.setQuantity(cant);
                    RawMaterial rawMaterialNew = new RawMaterial(rawMaterial.getId(),
                            rawMaterial.getName(), rawMaterial.getDescription(),
                            rawMaterial.getPrice(), rawMaterial.getQuantity(),
                            rawMaterial.getBestBy(), rawMaterial.getSupplierId());
                    try {
//                        
                        //estado de autocommit
                        if (conexionTransaccional.getAutoCommit()) {
                            conexionTransaccional.setAutoCommit(false);
                        }
                        rawMaterialDAO = new RawMaterialDAO(conexionTransaccional);
                        System.out.println("-> " + rawMaterialDAO.update(rawMaterialNew));
                        conexionTransaccional.commit();
                        JOptionPane.showMessageDialog(null, "PEDIDO REALIZADO");
                    } catch (SQLException ex) {
                        ex.printStackTrace(System.out);
                        //revertir la base de datos
                        System.out.println("ROLLBACK - BDD");
                        try {
                            conexionTransaccional.rollback();
                        } catch (SQLException ex1) {
                            ex1.printStackTrace(System.out);
                        }

                    }
                }
                try {
                    conexionTransaccional.commit();
                } catch (SQLException ex1) {
                    ex1.printStackTrace(System.out);
                }

            }
        } else {
            JOptionPane.showMessageDialog(null, "SELECCIONE EL PRODUCTO Y ASIGNE LA CANTIDAD");
        }
    }//GEN-LAST:event_jBOrderActionPerformed

    private void jBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackActionPerformed
        inventory = new Inventory();
        inventory.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnBackActionPerformed

    private void jCBRawMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBRawMaterialMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBRawMaterialMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactSupplier().setVisible(true);
            }
        });
    }

    public void insertItems() throws SQLException {
        try {
            conexionTransaccional = Connect.getConnection();
            //estado de autocommit
            if (conexionTransaccional.getAutoCommit()) {
                conexionTransaccional.setAutoCommit(false);
            }
            rawMaterialDAO = new RawMaterialDAO(conexionTransaccional);
            rawMaterials = rawMaterialDAO.select();
            System.out.println("PITO");

        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
            //revertir la base de datos
            System.out.println("ROLLBACK - BDD");
            try {
                conexionTransaccional.rollback();
            } catch (SQLException ex1) {
                ex1.printStackTrace(System.out);
            }
        }
        jCBRawMaterial.addItem("Seleccione");
        for (RawMaterial rawMaterial : rawMaterials) {
            jCBRawMaterial.addItem(rawMaterial.getName());
        }
    }

    public void showSupplier() throws SQLException {
        try {
            conexionTransaccional = Connect.getConnection();
            //estado de autocommit
            if (conexionTransaccional.getAutoCommit()) {
                conexionTransaccional.setAutoCommit(false);
            }
            supplierDAO = new SupplierDAO(conexionTransaccional);
            suppliers = supplierDAO.select();

        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
            //revertir la base de datos
            System.out.println("ROLLBACK - BDD");
            try {
                conexionTransaccional.rollback();
            } catch (SQLException ex1) {
                ex1.printStackTrace(System.out);
            }
        }
        for (RawMaterial rawMaterial : rawMaterials) {
            if (String.valueOf(jCBRawMaterial.getSelectedItem()).equals(rawMaterial.getName())) {
                for (Supplier supplier : suppliers) {
                    if (rawMaterial.getSupplierId() == supplier.getId()) {
                        jLSupplierName.setText(supplier.getName());
                        jLPhone.setText(supplier.getPhone());
                        jLEmail.setText(supplier.getEmail());
                    }

                }

            }

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBOrder;
    private javax.swing.JButton jBtnBack;
    private javax.swing.JComboBox<String> jCBRawMaterial;
    private javax.swing.JLabel jLDescription;
    private javax.swing.JLabel jLEmail;
    private javax.swing.JLabel jLPhone;
    private javax.swing.JLabel jLSupplierName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpRawMaterialQuantity;
    // End of variables declaration//GEN-END:variables
}
