/*
 * Delivery driver UI
 */
package ui;

import business.DeliveryDriverController;
import business.Validate;
import ui.components.*;
import domain.*;
import java.awt.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.*;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author Bryan Andagoya
 */
public final class DeliveryDriverUI extends javax.swing.JFrame {

    private DeliveryDriver deliveryDriver;
    private DefaultTableModel tableModel;
    private Fonts fonts = new Fonts();
    private java.util.List<Object[]> orders;
    private ArrayList<JTextField> dataFields = new ArrayList<>();
    private JPanel auxPanel;
    private JTableHeader tableHeader;
    private DefaultTableCellRenderer cellRender = new DefaultTableCellRenderer();

    /**
     * Creates new form DeliveryDriverUI
     *
     * @param deliveryDriver
     */
    public DeliveryDriverUI(DeliveryDriver deliveryDriver) {
        this.auxPanel = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
                g.drawImage(Icons.DELIVERY_BACKGROUND.getImage(), 0, 0, this);
            }
        };

        this.deliveryDriver = deliveryDriver;
        initComponents();
        configureWindow();
        configureComponents();
    }

    public void configureWindow() {
        setLocationRelativeTo(null);
    }

    public void configureComponents() {
        mainPanel.remove(btn_done);
        mainPanel.revalidate();
        mainPanel.repaint();
        fillDataFieldsList();

        tableHeader = tbl_orders.getTableHeader();
        tableModel = (DefaultTableModel) tbl_orders.getModel();
        customizeTableHeader();
        customizeColumns();
        fillFields();
        orders = DeliveryDriverController.getOrders(deliveryDriver.getId());
        fillTable();
    }

    public void fillDataFieldsList() {
        dataFields.add(txt_name);
        dataFields.add(txt_lastName);
        dataFields.add(txt_document);
        dataFields.add(txt_email);
        dataFields.add(txt_phone);
        dataFields.add(txt_address);
        dataFields.add(txt_licensePlate);
    }

    public void customizeTableHeader() {
        tableHeader.setFont(fonts.robotoBold.deriveFont(Font.PLAIN, 12));
        tableHeader.setBackground(new Color(243, 156, 18));
        tableHeader.setForeground(new Color(253, 254, 254));
    }

    public void customizeColumns() {
        cellRender.setHorizontalAlignment(JLabel.CENTER);

        for (int i = 0; i < tableModel.getColumnCount() - 1; i++) {
            tbl_orders.getColumnModel().getColumn(i).setCellRenderer(cellRender);
        }

    }

    public void fillFields() {
        lbl_user.setText(deliveryDriver.getUser());
        txt_name.setText(deliveryDriver.getName());
        txt_lastName.setText(deliveryDriver.getLastName());
        txt_document.setText(deliveryDriver.getDocument());
        txt_email.setText(deliveryDriver.getEmail());
        txt_phone.setText(deliveryDriver.getPhone());
        txt_address.setText(deliveryDriver.getAddress());
        txt_licensePlate.setText(deliveryDriver.getLicensePlate().toUpperCase());
    }

    public void fillTable() {
//        for (int i = 0; i < 10; i++) {
//            tableModel.addRow(new Object[]{i, "como", "estas", "yo", "bien", "brus", false});
//        }

        if (orders != null) {
            orders.forEach(tableModel::addRow);
        }
    }

    public void setFieldsEditable(boolean editable) {
        dataFields.forEach(field -> {
            field.setEditable(editable);
            if (editable) {
                field.setBackground(new Color(253, 254, 254));
            } else {
                field.setBackground(new Color(254, 249, 231));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = auxPanel;
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_orders = new javax.swing.JTable();
        btn_done = new javax.swing.JButton();
        btn_updateData = new javax.swing.JButton();
        txt_licensePlate = new javax.swing.JTextField();
        lbl_fieldLicensePlate = new javax.swing.JLabel();
        lbl_fieldDocument = new javax.swing.JLabel();
        lbl_fieldLastName = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        lbl_fieldEmail = new javax.swing.JLabel();
        lbl_fieldPhone = new javax.swing.JLabel();
        lbl_fieldAddress = new javax.swing.JLabel();
        lbl_fieldName1 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_lastName = new javax.swing.JTextField();
        txt_document = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_phone = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        btn_removeOrders = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ITSQMET BURGER");
        setIconImage(Icons.FRAME_ICON.getImage()
        );
        setMinimumSize(new java.awt.Dimension(790, 460));
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(254, 249, 231));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_orders.setBackground(new java.awt.Color(253, 254, 254));
        tbl_orders.setFont(fonts.robotoRegular.deriveFont(Font.PLAIN, 13)
        );
        tbl_orders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Factura", "Fecha", "Total", "Nombre Cliente", "Teléfono Cliente", "Dirección Cliente", "Entregado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_orders.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tbl_orders.setFillsViewportHeight(true);
        tbl_orders.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(tbl_orders);
        if (tbl_orders.getColumnModel().getColumnCount() > 0) {
            tbl_orders.getColumnModel().getColumn(0).setPreferredWidth(70);
            tbl_orders.getColumnModel().getColumn(3).setPreferredWidth(147);
            tbl_orders.getColumnModel().getColumn(4).setPreferredWidth(100);
            tbl_orders.getColumnModel().getColumn(5).setPreferredWidth(130);
            tbl_orders.getColumnModel().getColumn(6).setPreferredWidth(70);
        }

        mainPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 670, 340));

        btn_done.setBackground(new java.awt.Color(245, 176, 65));
        btn_done.setFont(fonts.robotoBold.deriveFont(Font.PLAIN, 18));
        btn_done.setForeground(new java.awt.Color(255, 255, 255));
        btn_done.setText("Hecho");
        btn_done.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_done.setBorderPainted(false);
        btn_done.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_done.setFocusPainted(false);
        btn_done.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_doneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_doneMouseExited(evt);
            }
        });
        btn_done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doneActionPerformed(evt);
            }
        });
        mainPanel.add(btn_done, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, -1, -1));

        btn_updateData.setBackground(new java.awt.Color(231, 76, 60));
        btn_updateData.setFont(fonts.robotoBold.deriveFont(Font.PLAIN, 18));
        btn_updateData.setForeground(new java.awt.Color(255, 255, 255));
        btn_updateData.setText("Actualizar");
        btn_updateData.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_updateData.setBorderPainted(false);
        btn_updateData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_updateData.setFocusPainted(false);
        btn_updateData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_updateDataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_updateDataMouseExited(evt);
            }
        });
        btn_updateData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateDataActionPerformed(evt);
            }
        });
        mainPanel.add(btn_updateData, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));

        txt_licensePlate.setEditable(false);
        txt_licensePlate.setBackground(new java.awt.Color(254, 249, 231));
        txt_licensePlate.setFont(fonts.robotoRegular.deriveFont(Font.PLAIN, 14));
        txt_licensePlate.setText("Nombre");
        txt_licensePlate.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        txt_licensePlate.setSelectedTextColor(new java.awt.Color(253, 254, 254));
        txt_licensePlate.setSelectionColor(new java.awt.Color(229, 152, 102));
        txt_licensePlate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_licensePlateKeyTyped(evt);
            }
        });
        mainPanel.add(txt_licensePlate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 200, 30));

        lbl_fieldLicensePlate.setFont(fonts.robotoMedium.deriveFont(Font.PLAIN, 14)
        );
        lbl_fieldLicensePlate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_fieldLicensePlate.setText("Placa vehicular:");
        mainPanel.add(lbl_fieldLicensePlate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 110, 30));

        lbl_fieldDocument.setFont(fonts.robotoMedium.deriveFont(Font.PLAIN, 14)
        );
        lbl_fieldDocument.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_fieldDocument.setText("CI.:");
        mainPanel.add(lbl_fieldDocument, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 90, 30));

        lbl_fieldLastName.setFont(fonts.robotoMedium.deriveFont(Font.PLAIN, 14)
        );
        lbl_fieldLastName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_fieldLastName.setText("Apellido:");
        mainPanel.add(lbl_fieldLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 90, 30));

        lbl_user.setFont(fonts.robotoBlack.deriveFont(Font.BOLD, 20)
        );
        lbl_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_user.setText("Usuario");
        mainPanel.add(lbl_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 160, 30));

        lbl_fieldEmail.setFont(fonts.robotoMedium.deriveFont(Font.PLAIN, 14)
        );
        lbl_fieldEmail.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_fieldEmail.setText("Email:");
        mainPanel.add(lbl_fieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 90, 30));

        lbl_fieldPhone.setFont(fonts.robotoMedium.deriveFont(Font.PLAIN, 14)
        );
        lbl_fieldPhone.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_fieldPhone.setText("Teléfono:");
        mainPanel.add(lbl_fieldPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 90, 30));

        lbl_fieldAddress.setFont(fonts.robotoMedium.deriveFont(Font.PLAIN, 14)
        );
        lbl_fieldAddress.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_fieldAddress.setText("Dirección:");
        mainPanel.add(lbl_fieldAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 90, 30));

        lbl_fieldName1.setFont(fonts.robotoMedium.deriveFont(Font.PLAIN, 14)
        );
        lbl_fieldName1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_fieldName1.setText("Nombre:");
        mainPanel.add(lbl_fieldName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 90, 30));

        txt_name.setEditable(false);
        txt_name.setBackground(new java.awt.Color(254, 249, 231));
        txt_name.setFont(fonts.robotoRegular.deriveFont(Font.PLAIN, 14));
        txt_name.setText("Nombre");
        txt_name.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        txt_name.setSelectedTextColor(new java.awt.Color(253, 254, 254));
        txt_name.setSelectionColor(new java.awt.Color(229, 152, 102));
        mainPanel.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 200, 30));

        txt_lastName.setEditable(false);
        txt_lastName.setBackground(new java.awt.Color(254, 249, 231));
        txt_lastName.setFont(fonts.robotoRegular.deriveFont(Font.PLAIN, 14));
        txt_lastName.setText("Nombre");
        txt_lastName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        txt_lastName.setSelectedTextColor(new java.awt.Color(253, 254, 254));
        txt_lastName.setSelectionColor(new java.awt.Color(229, 152, 102));
        mainPanel.add(txt_lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 200, 30));

        txt_document.setEditable(false);
        txt_document.setBackground(new java.awt.Color(254, 249, 231));
        txt_document.setFont(fonts.robotoRegular.deriveFont(Font.PLAIN, 14));
        txt_document.setText("Nombre");
        txt_document.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        txt_document.setSelectedTextColor(new java.awt.Color(253, 254, 254));
        txt_document.setSelectionColor(new java.awt.Color(229, 152, 102));
        txt_document.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_documentKeyTyped(evt);
            }
        });
        mainPanel.add(txt_document, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 200, 30));

        txt_email.setEditable(false);
        txt_email.setBackground(new java.awt.Color(254, 249, 231));
        txt_email.setFont(fonts.robotoRegular.deriveFont(Font.PLAIN, 14));
        txt_email.setText("Nombre");
        txt_email.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        txt_email.setSelectedTextColor(new java.awt.Color(253, 254, 254));
        txt_email.setSelectionColor(new java.awt.Color(229, 152, 102));
        mainPanel.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 200, 30));

        txt_phone.setEditable(false);
        txt_phone.setBackground(new java.awt.Color(254, 249, 231));
        txt_phone.setFont(fonts.robotoRegular.deriveFont(Font.PLAIN, 14));
        txt_phone.setText("Nombre");
        txt_phone.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        txt_phone.setSelectedTextColor(new java.awt.Color(253, 254, 254));
        txt_phone.setSelectionColor(new java.awt.Color(229, 152, 102));
        txt_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_phoneKeyTyped(evt);
            }
        });
        mainPanel.add(txt_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 200, 30));

        txt_address.setEditable(false);
        txt_address.setBackground(new java.awt.Color(254, 249, 231));
        txt_address.setFont(fonts.robotoRegular.deriveFont(Font.PLAIN, 14));
        txt_address.setText("Nombre");
        txt_address.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        txt_address.setSelectedTextColor(new java.awt.Color(253, 254, 254));
        txt_address.setSelectionColor(new java.awt.Color(229, 152, 102));
        mainPanel.add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 200, 30));

        btn_removeOrders.setBackground(new java.awt.Color(231, 76, 60));
        btn_removeOrders.setFont(fonts.robotoBold.deriveFont(Font.PLAIN, 18));
        btn_removeOrders.setForeground(new java.awt.Color(255, 255, 255));
        btn_removeOrders.setText("Quitar pedidos entregados");
        btn_removeOrders.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_removeOrders.setBorderPainted(false);
        btn_removeOrders.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_removeOrders.setFocusPainted(false);
        btn_removeOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_removeOrdersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_removeOrdersMouseExited(evt);
            }
        });
        btn_removeOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeOrdersActionPerformed(evt);
            }
        });
        mainPanel.add(btn_removeOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, -1, -1));

        jButton1.setIcon(Icons.LOG_OUT);
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        mainPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 48, 48));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1077, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_updateDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateDataMouseEntered
        if (btn_updateData.isEnabled()) {
            btn_updateData.setBackground(new Color(203, 67, 53));
        }
    }//GEN-LAST:event_btn_updateDataMouseEntered

    private void btn_updateDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateDataMouseExited
        btn_updateData.setBackground(new Color(231, 76, 60));
    }//GEN-LAST:event_btn_updateDataMouseExited

    private void btn_updateDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateDataActionPerformed

        mainPanel.remove(btn_updateData);
        mainPanel.add(btn_updateData, new AbsoluteConstraints(45, 430, -1, -1), 1);
        mainPanel.add(btn_done, new AbsoluteConstraints(150, 430, -1, -1), 1);
        mainPanel.revalidate();
        mainPanel.repaint();

        btn_updateData.setEnabled(false);
        setFieldsEditable(true);
    }//GEN-LAST:event_btn_updateDataActionPerformed

    private void btn_removeOrdersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_removeOrdersMouseEntered
        btn_removeOrders.setBackground(new Color(203, 67, 53));
    }//GEN-LAST:event_btn_removeOrdersMouseEntered

    private void btn_removeOrdersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_removeOrdersMouseExited
        btn_removeOrders.setBackground(new Color(231, 76, 60));
    }//GEN-LAST:event_btn_removeOrdersMouseExited

    private void btn_removeOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeOrdersActionPerformed
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            if ((boolean) tableModel.getValueAt(i, 6)) {
                tableModel.removeRow(i--);
            }
        }
    }//GEN-LAST:event_btn_removeOrdersActionPerformed

    private void btn_doneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_doneMouseEntered
        btn_done.setBackground(new Color(243, 156, 18));
    }//GEN-LAST:event_btn_doneMouseEntered

    private void btn_doneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_doneMouseExited
        btn_done.setBackground(new Color(245, 176, 65));
    }//GEN-LAST:event_btn_doneMouseExited

    private void btn_doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_doneActionPerformed
        if (DeliveryDriverController.validateFields(this, deliveryDriver.getId(),
                txt_name, txt_lastName, txt_document, txt_email, txt_phone,
                txt_address, txt_licensePlate)) {

            if (DeliveryDriverController.updateDeliveryDriver(deliveryDriver.getId(), dataFields)) {
                JOptionPane.showMessageDialog(this,
                        "Tus datos se han actualizado satisfactoriamente",
                        "Exito",
                        JOptionPane.ERROR_MESSAGE,
                        Icons.SUCCESS_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Your computer has a virus",
                        "Error",
                        JOptionPane.ERROR_MESSAGE,
                        Icons.ERROR_MESSAGE);
            }

            setFieldsEditable(false);
            mainPanel.remove(btn_done);
            mainPanel.remove(btn_updateData);
            mainPanel.add(btn_updateData, new AbsoluteConstraints(100, 430, -1, -1), 1);
            mainPanel.revalidate();
            mainPanel.repaint();

            btn_updateData.setEnabled(true);
        }
    }//GEN-LAST:event_btn_doneActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new LogInUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_documentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_documentKeyTyped
        if (txt_document.getText().length() < 10) {
            Validate.allowDigits(evt);
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_txt_documentKeyTyped

    private void txt_phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_phoneKeyTyped
        if (txt_phone.getText().length() < 10) {
            Validate.allowDigits(evt);
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_txt_phoneKeyTyped

    private void txt_licensePlateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_licensePlateKeyTyped
        char character = evt.getKeyChar();

        if (txt_licensePlate.getText().length() >= 3) {
            if (!Character.isDigit(character) || txt_licensePlate.getText().length() == 7) {
                evt.consume();
            }
        } else {
            if (!(Character.isLetter(character))) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txt_licensePlateKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DeliveryDriverUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DeliveryDriverUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DeliveryDriverUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DeliveryDriverUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeliveryDriverUI(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_done;
    private javax.swing.JButton btn_removeOrders;
    private javax.swing.JButton btn_updateData;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_fieldAddress;
    private javax.swing.JLabel lbl_fieldDocument;
    private javax.swing.JLabel lbl_fieldEmail;
    private javax.swing.JLabel lbl_fieldLastName;
    private javax.swing.JLabel lbl_fieldLicensePlate;
    private javax.swing.JLabel lbl_fieldName1;
    private javax.swing.JLabel lbl_fieldPhone;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable tbl_orders;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_document;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_lastName;
    private javax.swing.JTextField txt_licensePlate;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_phone;
    // End of variables declaration//GEN-END:variables
}
