/*
 * JFrame
 */
package com.desarrollo.store;

import java.text.DecimalFormat;
import java.text.ParseException;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bryan Andagoya
 */
public final class Invoice extends javax.swing.JFrame {

    //Fields
    DefaultTableModel invoiceModel = new DefaultTableModel();
    DecimalFormat formatter = new DecimalFormat("###,###.00");
    JFrame mainFrame;

    /**
     * Creates new form Factura
     */
    public Invoice() {
        initComponents();
        configureFrame();
        configureInvoiceTable();
    }

    /**
     * Configures the Frame.
     */
    public void configureFrame() {
        setLocationRelativeTo(null);

        setIconImage(new ImageIcon("src/main/java/com/desarrollo/images/icon.png")
                .getImage());
    }

    /**
     * Configures the invoice table and its model.
     */
    public void configureInvoiceTable() {
        tbl_invoice.setModel(invoiceModel);

        invoiceModel.addColumn("Detalle");
        invoiceModel.addColumn("Cantidad");
        invoiceModel.addColumn("Precio Unitario");
        invoiceModel.addColumn("Precio Total");
    }

    /**
     * Displays the invoice and the total.
     *
     * @param detailsTable The table that contains the purchase details.
     * @param subtotalLabel The label that contains the purchase subtotal.
     * @param mainFrame The main frame.
     * @param invoiceNumber The invoice number.
     */
    public void displayInvoice(JTable detailsTable, JLabel subtotalLabel, JFrame mainFrame, int invoiceNumber) {
        double subtotal;
        double iva;
        double total;
        this.mainFrame = mainFrame;

        for (int i = 0; i < detailsTable.getRowCount(); i++) {
            invoiceModel.addRow(new Object[]{
                detailsTable.getValueAt(i, 0),
                detailsTable.getValueAt(i, 4),
                detailsTable.getValueAt(i, 5),
                detailsTable.getValueAt(i, 6),});
        }

        txt_subtotal.setText(subtotalLabel.getText());

        try {
            subtotal = formatter.parse(subtotalLabel.getText()).doubleValue();
            iva = subtotal * 0.12;
            total = subtotal + iva;

            txt_iva.setText(formatter.format(iva));
            txt_total.setText(formatter.format(total));
        } catch (ParseException ex) {
            System.out.println(ex);
        }

        lbl_invoiceTitle.setText("Factura N° " + invoiceNumber);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_invoiceTitle = new javax.swing.JLabel();
        lbl_address = new javax.swing.JLabel();
        lbl_document = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        txt_document = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_invoice = new javax.swing.JTable();
        lbl_iva = new javax.swing.JLabel();
        txt_subtotal = new javax.swing.JTextField();
        lbl_subtotal = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        lbl_total = new javax.swing.JLabel();
        txt_iva = new javax.swing.JTextField();
        separator = new javax.swing.JSeparator();
        lbl_thanks = new javax.swing.JLabel();
        btn_send = new javax.swing.JButton();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Factura");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(251, 252, 252));
        jPanel1.setLayout(null);

        lbl_invoiceTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_invoiceTitle.setForeground(new java.awt.Color(0, 153, 255));
        lbl_invoiceTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_invoiceTitle.setText("FACTURA ");
        jPanel1.add(lbl_invoiceTitle);
        lbl_invoiceTitle.setBounds(0, 20, 464, 32);

        lbl_address.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_address.setText("Dirección:");
        jPanel1.add(lbl_address);
        lbl_address.setBounds(44, 209, 67, 20);

        lbl_document.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_document.setText("Cédula:");
        jPanel1.add(lbl_document);
        lbl_document.setBounds(44, 128, 50, 20);

        lbl_email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_email.setText("Email:");
        jPanel1.add(lbl_email);
        lbl_email.setBounds(44, 169, 40, 20);

        lbl_name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_name.setText("Nombre:");
        jPanel1.add(lbl_name);
        lbl_name.setBounds(44, 84, 60, 20);

        txt_document.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_document.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_documentKeyTyped(evt);
            }
        });
        jPanel1.add(txt_document);
        txt_document.setBounds(166, 120, 247, 30);

        txt_email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txt_email);
        txt_email.setBounds(166, 161, 247, 30);

        txt_address.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txt_address);
        txt_address.setBounds(166, 201, 247, 30);

        txt_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txt_name);
        txt_name.setBounds(166, 76, 247, 30);

        tbl_invoice.setBackground(new java.awt.Color(251, 252, 252));
        tbl_invoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_invoice);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(6, 257, 452, 196);

        lbl_iva.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_iva.setText("IVA 12%:");
        jPanel1.add(lbl_iva);
        lbl_iva.setBounds(250, 530, 59, 20);

        txt_subtotal.setEditable(false);
        txt_subtotal.setBackground(new java.awt.Color(235, 245, 251));
        txt_subtotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txt_subtotal);
        txt_subtotal.setBounds(340, 482, 120, 30);

        lbl_subtotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_subtotal.setText("SUBTOTAL");
        jPanel1.add(lbl_subtotal);
        lbl_subtotal.setBounds(250, 490, 71, 20);

        txt_total.setEditable(false);
        txt_total.setBackground(new java.awt.Color(235, 245, 251));
        txt_total.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txt_total);
        txt_total.setBounds(340, 562, 120, 30);

        lbl_total.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_total.setText("TOTAL");
        jPanel1.add(lbl_total);
        lbl_total.setBounds(250, 570, 44, 20);

        txt_iva.setEditable(false);
        txt_iva.setBackground(new java.awt.Color(235, 245, 251));
        txt_iva.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txt_iva);
        txt_iva.setBounds(340, 522, 120, 30);
        jPanel1.add(separator);
        separator.setBounds(0, 470, 464, 10);

        lbl_thanks.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lbl_thanks.setForeground(new java.awt.Color(0, 153, 204));
        lbl_thanks.setText("Gracias por su confianza");
        jPanel1.add(lbl_thanks);
        lbl_thanks.setBounds(10, 490, 230, 25);

        btn_send.setBackground(new java.awt.Color(127, 179, 213));
        btn_send.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_send.setText("Enviar");
        btn_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendActionPerformed(evt);
            }
        });
        jPanel1.add(btn_send);
        btn_send.setBounds(60, 550, 110, 31);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendActionPerformed
        boolean validDocument = txt_document.getText().matches("\\d{10}");
        boolean validEmail = txt_email.getText().matches("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");

        if (txt_name.getText().isEmpty()
                || txt_document.getText().isEmpty()
                || txt_email.getText().isEmpty()
                || txt_address.getText().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Información incompleta",
                    "Error", JOptionPane.ERROR_MESSAGE);

        } else {

            if (validDocument) {
                if (validEmail) {

                    JOptionPane.showMessageDialog(this, "La factura se ha enviado satisfactoriamente",
                            "Enviado", JOptionPane.INFORMATION_MESSAGE);

                    dispose();
                    mainFrame.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Correo electrónico inválido",
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Número de cédula inválida",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }

        }

    }//GEN-LAST:event_btn_sendActionPerformed

    private void txt_documentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_documentKeyTyped
        int keyChar = (int) evt.getKeyChar();

        if (!(keyChar >= 48 && keyChar <= 57)) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_documentKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Invoice().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_send;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_address;
    private javax.swing.JLabel lbl_document;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_invoiceTitle;
    private javax.swing.JLabel lbl_iva;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_subtotal;
    private javax.swing.JLabel lbl_thanks;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JSeparator separator;
    private javax.swing.JTable tbl_invoice;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_document;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_iva;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_subtotal;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
